apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    deployment.kubernetes.io/revision: "${CODEBUILD_BUILD_NUMBER}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ${ECR_URI}:${CODEBUILD_BUILD_NUMBER}
        ports:
        - containerPort: 80
